# file: postgresql/tasks/extensions.yml

- import_tasks: extensions/contrib.yml
  when: postgresql_ext_install_contrib
- import_tasks: extensions/dev_headers.yml
  when: postgresql_ext_install_dev_headers
- import_tasks: extensions/postgis.yml
  when: postgresql_ext_install_postgis
- import_tasks: extensions/extra_packages.yml
  when: postgresql_ext_install_extra_packages
