# file: postgresql/tasks/install_dnf.yml

# The standard ca-certs are needed because  without them dnf will fail to
# validate www.postgresql.org (or probably any other source).

  - block:
      - name: PostgrSQL | Install all the required dependencies | dnf
        dnf:
          name: "ca-certificates, python*-pycurl, glibc-common, python*-libselinux, python*-psycopg2, glibc-locale-source"
          state: present

      #--- The package manager installed psycopg2 release 2.8.8 on Fedora 33 is not compatible with postgres < 10
      #--- This issue will probably spread to other distributions when the package based installation of
      #--- psycopg2 catches up with more recent releases
      - name: PIP install psycopg2-binary on Fedora 33 only if postgresql version < 10
        pip:
          name: psycopg2-binary
        when: postgresql_version_terse | int <= 96 and postgresql_version_terse | int >= 90 and ansible_distribution == 'Fedora' and ansible_distribution_major_version

      - name: PostgreSQL | Add yum Repository | dnf
        yum_repository:
          name: postgresql
          state: present
          description: postgresql yum repo
          baseurl: "{{ postgresql_dnf_repository_baseurl }}"
          gpgkey: "{{ postgresql_dnf_repository_gpgkey }}"
        when: postgresql_install_repository

      - name: PostgreSQL | Install PostgreSQL | dnf
        dnf:
          name: "postgresql{{ postgresql_version_terse }}-server,postgresql{{ postgresql_version_terse }},postgresql{{ postgresql_version_terse }}-contrib"
          state: present
        environment: "{{ postgresql_env }}"

      - name: PostgreSQL | PGTune | dnf
        dnf:
          name: pgtune
          state: present
        environment: "{{ postgresql_env }}"
        when: postgresql_pgtune
