# file: postgresql/tasks/install_yum.yml

# The standard ca-certs are needed because  without them apt_key will fail to
# validate www.postgresql.org (or probably any other source).

  - block:
      - name: PostgreSQL | Install all the required dependencies
        yum:
<<<<<<< HEAD
          name: ["ca-certificates", "python-psycopg2", "python-pycurl", "glibc-common", "epel-release", "libselinux-python"]
=======
          name: ["ca-certificates","python-psycopg2", "python-pycurl", "glibc-common","epel-release","libselinux-python"]
>>>>>>> 9ae74d4f97f656609dd748f363088e9f12ab5582
          state: present

      - name: PostgreSQL | Add PostgreSQL repository
        yum:
          name: "{{ postgresql_yum_repository_url }}"
          state: present

      - name: PostgreSQL | Install PostgreSQL
        yum:
          name: "{{ item }}"
          state: present
        environment: "{{ postgresql_env }}"
        with_items:
          - "postgresql{{ postgresql_version_terse }}-server"
          - "postgresql{{ postgresql_version_terse }}"
          - "postgresql{{ postgresql_version_terse }}-contrib"
<<<<<<< HEAD

      - name: PostgreSQL | PGTune
        yum:
          name: pgtune
          state: present
        environment: "{{ postgresql_env }}"
        when: postgresql_pgtune
=======

      - name: PostgreSQL | PGTune
        yum:
          name: pgtune
          state: present
        environment: "{{ postgresql_env }}"
        when: postgresql_pgtune

>>>>>>> 9ae74d4f97f656609dd748f363088e9f12ab5582
