# file: postgresql/tasks/privileges.yml

- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: "{{ postgresql_service_name }}"
    state: started

- name: PostgreSQL | Update the user privileges
  postgresql_user:
    name: "{{item.name}}"
    db: "{{item.db | default(omit)}}"
    port: "{{postgresql_port}}"
    priv: "{{item.priv | default(omit)}}"
    state: present
    login_host: "{{item.host | default(omit)}}"
    login_user: "{{postgresql_admin_user}}"
    role_attr_flags: "{{item.role_attr_flags | default(omit)}}"
  sudo: yes
  sudo_user: "{{postgresql_admin_user}}"
  with_items: postgresql_user_privileges

- name: PostgreSQL | Make sure the PostgreSQL privileges are present
  postgresql_privs:
    database: "{{ item.db }}"
    grant_option: "{{ item.grant | default(no) }}"
    host: "{{ item.host | default(\"127.0.0.1\") }}"
    login: "{{ item.login | default(postgresql_admin_user) }}"
    objs: "{{ item.objs | default(omit) }}"
    password: "{{ item.password | default(\"\") }}"
    privs: "{{ item.privs | default(\"ALL\") }}"
    roles: "{{ item.roles | default(\"PUBLIC\") }}"
    schema: "{{ item.schema | default(omit) }}"
    state: "{{ item.state | default(\"present\") }}"
    type: "{{ item.type | default(\"table\") }}"
  sudo: yes
  sudo_user: "{{postgresql_admin_user}}"
  with_items: postgresql_db_priveleges