# file: postgresql/handlers/main.yml

- name: reload postgresql
  include_tasks: "{{ role_path }}/handlers/reload.yml"

- name: restart postgresql
  include_tasks: "{{ role_path }}/handlers/restart.yml"
