# file: postgresql/handlers/main.yml

  - name: restart postgresql with service
    service:
      name: "{{ postgresql_service_name }}"
      state: restarted
      enabled: yes

  - name: restart postgresql with systemd
    systemd:
      name: "{{ postgresql_service_name }}"
      state: restarted
      enabled: yes
    when: ansible_service_mgr == 'systemd'
<<<<<<< HEAD
=======
 
>>>>>>> 9ae74d4f97f656609dd748f363088e9f12ab5582
