---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
#  yamllint .
#  ansible-lint
platforms:
  - name: postgresql-11
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
  - name: postgresql-12
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
  - name: postgresql-13
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
  - name: postgresql-14
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
  - name: postgresql-15
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare:  ${MOLECULE_PLAYBOOK:-../../tests/prepare.yml}
    converge: ${MOLECULE_PLAYBOOK:-../../tests/playbook.yml}
  inventory:
    host_vars:
      postgresql-11:
        postgresql_version: 11
      postgresql-12:
        postgresql_version: 12
      postgresql-13:
        postgresql_version: 13
      postgresql-14:
        postgresql_version: 14
      postgresql-15:
        postgresql_version: 15
verifier:
  name: ansible
