---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
#  yamllint .
#  ansible-lint
platforms:
  - name: postgresql-14
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare:  ${MOLECULE_PLAYBOOK:-../../tests/prepare.yml}
    converge: ${MOLECULE_PLAYBOOK:-../../tests/playbook.yml}
  inventory:
    host_vars:
      postgresql-14:
        postgresql_version: 14
verifier:
  name: ansible
