# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '35 23 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 90
        days-before-close: 60
        exempt-issue-labels: bug
        exempt-pr-labels: bug
        stale-issue-label: "stale"
        stale-pr-label: "stale"
        stale-issue-message: |
          This issue has been marked 'stale' due to lack of recent activity. If there is no further activity, the issue will be closed in another 30 days. Thank you for your contribution!
        close-issue-message: |
          This issue has been closed due to inactivity. If you feel this is in error, please reopen the issue or file a new issue with the relevant details.
        stale-pr-message: |
          This pr has been marked 'stale' due to lack of recent activity. If there is no further activity, the issue will be closed in another 30 days. Thank you for your contribution!
        close-pr-message: |
          This pr has been closed due to inactivity. If you feel this is in error, please reopen the issue or file a new issue with the relevant details.
